AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25
